# Generated by Django 6.0.1 on 2026-01-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'Naqd pul'), ('CARD', 'Bank kartasi'), ('OTHER', 'Boshqa')], default='CARD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'AQSH Dollari')], default='UZS', max_length=3)),
                ('icon', models.CharField(default='wallet', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
