# Generated by Django 6.0.1 on 2026-01-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
