# Generated by Django 6.0.1 on 2026-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_original_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_in_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
